#!/bin/bash

if [ ! -e cluster_analysis.1.Rdata ]
then
	R --no-save < cluster_analysis.1.R #>& cluster_analysis.1.log
fi

if [ ! -e cluster_analysis.2.Rdata ]
then
	R --no-save < cluster_analysis.2.R #>& cluster_analysis.2.log
fi

# get the upstream sequences
~/bcutil/bcutil get_upstream 5G.genbank.gff 5G.genome.fa -2 150 8 > 5G.upstream.tab
# create a background model from the entire genome
~/meme/bin/fasta-get-markov -m 8 5G.genome.fa > 5G.genome.bfile

if [ ! -e cluster_analysis.3.Rdata ]
then
	R --no-save < cluster_analysis.3.R #>& cluster_analysis.3.log
fi

