#!/bin/bash

if [ ! -e cluster_analysis.1.Rdata ]
then
	R --no-save < cluster_analysis.1.R #>& cluster_analysis.1.log
fi

if [ ! -e cluster_analysis.2.Rdata ]
then
	R --no-save < cluster_analysis.2.R #>& cluster_analysis.2.log
fi

if [ ! -e cluster_analysis.3.Rdata ]
then
	R --no-save < cluster_analysis.3.R #>& cluster_analysis.3.log
fi

