#!/bin/bash

if [ ! -e cluster_analysis.1.Rdata ]
then
	R --no-save < cluster_analysis.1.R #>& cluster_analysis.1.log
fi

if [ ! -e cluster_analysis.2.Rdata ]
then
	R --no-save < cluster_analysis.2.R #>& cluster_analysis.2.log
fi

~/bcutil/bcutil get_upstream 5G.genbank.gff 5G.genome.fa -2 150 8 | awk -F'\t' '{ if (on) { printf(">%s\n%s\n", $1, $2); } if ($1 == "locus_tag") { on = 1; }  }' > 5G.upstream.fa

if [ ! -e cluster_analysis.3.Rdata ]
then
	R --no-save < cluster_analysis.3.R #>& cluster_analysis.3.log
fi

